### ISSUE TITLE
Contacts not populating

### ISSUE THREAD

**Issue by FilipinaW** [ringcentral/rc-unified-crm-extension#1]
Our contact list is not picking up Pipedrive contacts, so not linking it in history and not able to even test if we can log calls.  Only options are RC contacts - All/Personal/Comany/Call Queues.  No Pipedrive listed.

**Comment by DaKingKong** [comment]
@FilipinaW Please have a look at https://www.youtube.com/watch?v=Ywb__BgEGXk , and make sure it's installed and authorized properly.

**Comment by FilipinaW** [comment]
Hi @DaKingKong .  I uninstalled and followed your instructions precisely to reinstall,  and it is still not showing any Pipedrive contacts.  Pipedrive shows authorized, yet only RingCentral contacts are listed.  It is also very weird as some of the history is linking random contacts FROM Pipedrive as secondary contact for phone numbers, even though the match is incorrect...  So some progress following your instructions (icon to add calls history shows up now and it didn't before), but still not working properly.  
![image](https://github.com/ringcentral/rc-unified-crm-extension/assets/47257281/3e5178e8-b176-4ec8-b876-cf8972d55dd0)

**Comment by FilipinaW** [comment]
if you look at this screen shot, call was with Mary Jo from our company - yet it's pulling random contact from Pipedrive that does not have the same number as Mary Jo:  
![image](https://github.com/ringcentral/rc-unified-crm-extension/assets/47257281/03b87d14-f6be-4563-ac05-e8ee177a0044)

**Comment by DaKingKong** [comment]
@FilipinaW Sorry I misunderstood you question. You are right, Pipedrive contacts are not in extension's contact list.

The contact info is fetched real-time from Pipedrive API when needed so to avoid frequent syncing-to-local process, especially for users who have thousands of contacts.

**Comment by FilipinaW** [comment]
OK, so it works different than chrome extension we used before.  However the new version is NOT fetching the real time data for us.  No contacts show correctly in history, and when I try to add call history, it tells me that phone number is not found in Pipedrive, even though it is tagged to the contact in Pipedrive.    I'll have to get my team to roll back to other version till this works again, as we mainly use this extension to log calls.

**Comment by DaKingKong** [comment]
@FilipinaW 
The issue you described feels like a phone number matching issue. As you might notice the error message from the extension would say 'cannot find contact for +1xxxxxxxx' but on Pipedrive you might have it as (xxx) xxx-xxxx.

There was a patch (on the server side, so no download needed) already released a few days ago that fixed the phone number matcher. Do you want to check again and see if it works?

**Comment by DaKingKong** [comment]
@FilipinaW Yeah it feels like a problem that I haven't thought of. Let me try some test cases according to your description. And at the meantime, quick check, do you still have all those issue above (cannot find contact etc.)?

**Comment by DaKingKong** [comment]
@FilipinaW I'm gradually improving this number matching according to different use cases from different region and configurations. 

The view details may not work for non-RC contacts at the moment. It's on our roadmap.

Let's solve your extension number matching problems first. Is it the one that puts your colleague and a contact together? I'll need a test plan for that. Here's my plan, please check for me if that matches your case:

1. Have an internal contact with extension eg. 224 , and a Pipedrive contact with number eg. (224) 3452-2334
2. Call the internal contact
3. Check if call history will fetch both contacts while it should only fetch the internal contact

**Comment by FilipinaW** [comment]
I did a test call after I added a test contact with phone number (224) 345-2334, and it is fetching same information as before - my coworker's name and the original contact from Pipedrive as per my screenshot last week.  The new test contact is not showing up in the dropdown.

**Comment by DaKingKong** [comment]
@FilipinaW  It should be good now, please try again

**Comment by FilipinaW** [comment]
Yes, it seems to be working now!  Extension calls are not matching to those other contacts/numbers now.
