### ISSUE TITLE
New chrome webstore URL format needed.

### ISSUE THREAD

**Issue by YesThatAllen** [ringcentral/rc-unified-crm-extension#11]
I noticed that the URL I was sent to to install the app has a warning. "This version of the Chrome Web Store will be discontinued in January" [2023]

The offending URL is
`https://chrome.google.com/webstore/detail/ringcentral-crm-extension/kkhkjhafgdlihndcbnebljipgkandkhh`

The following URL works, and doesn't have the warning:

https://chromewebstore.google.com/detail/ringcentral-crm-extension/kkhkjhafgdlihndcbnebljipgkandkhh

Updating the docs should take care of this.

Hope this is helpful!

**Comment by DaKingKong** [comment]
Thanks @YesThatAllen . I'll update it in next release.
