### ISSUE TITLE
Clio not authorizing

### ISSUE THREAD

**Issue by tdarcy1124** [ringcentral/rc-unified-crm-extension#3]
I go through the steps to authorize Clio to see the RingCentral information and log the calls into Clio, and it says it's authorized, but when I close the window and re-open the window it is no longer authorized (if it ever were). I try leaving the window open, and it still doesn't log my calls into Clio.

**Comment by DaKingKong** [comment]
@tdarcy1124 

Please try this and send me the logs:
1. Open the extension
2. Press F12 to call out developer console (DevTools) and switch to "Console" tab
3. On the extension, do authorization
4. Check developer console and see if there's any red text like in the screenshot. Those are the error logs. Please post them here or send them to da.kong@ringcentral.com . 

![image](https://github.com/ringcentral/rc-unified-crm-extension/assets/41028904/39f00ffc-e769-47d2-8d55-d75bb4285b1f)

**Comment by tdarcy1124** [comment]
Dear DaKingKong,

Here is the screenshot per your request.

Sincerely,

[photo]<http://www.thinklegalpc.com/>
Taylor E. Darcy
Attorney at Law, Think Legal, P.C.

[icon]  www.thinklegalpc.com<https://www.thinklegalpc.com/>  |  [icon]   ***@***.******@***.***>

[icon]  7220 Trade Street, Suite 101, San Diego, CA 92121<https://maps.google.com/?q=7220%20Trade%20Street,%20Suite%20101,%20San%20Diego,%20CA%2092121>

[icon]  (858) 956-5878<tel:(858)%20956-5878>  |  [icon]   (858) 956-5879<fax:(858)%20956-5879>
[facebook]<https://facebook.com/thinklegalpc>
[instagram]<https://instagram.com/thinklegalpc>
[linkedin]<https://linkedin.com/in/taylordarcyesq>
[twitter]<https://twitter.com/thinklegalpc>
[youtube]<https://youtube.com/c/thinklegalpc>
***@***.***/>

**Comment by DaKingKong** [comment]
@tdarcy1124 I don't see any image here....you could send it to my email though. It doesn't need to be under this Github issue.

**Comment by tdarcy1124** [comment]
Here it is again

Taylor E. Darcy, JD, MBA
Attorney/CEO
Think Legal, P.C.
(858) 956-5878
________________________________

**Comment by DaKingKong** [comment]
@tdarcy1124 Still don't see it. I guess that you are using email to reply Github issue comments, which might not work.

Try this:

Compose a new email with your screenshot and send it to da.kong@ringcentral.com
