### ISSUE TITLE
unable to sign in to Ringcentral CRM Extension

### ISSUE THREAD

**Issue by mikef723** [ringcentral/rc-unified-crm-extension#39]
Started having an issue today where I cannot sign in to RC CRM Extension.  I am including a screenshot of what happens when I attempt to sign in.  

![Screenshot 2024-07-08 144424](https://github.com/ringcentral/rc-unified-crm-extension/assets/70021227/d4844d5d-d559-4ef4-9304-132ce3ab6456)

**Comment by DaKingKong** [comment]
@mikef723 

I'm working on a patch ATM. For the time being, please try the following:

1. Log in to Redtail
2. Open the extension from Redtail page
3. Try sign in

If not working, please right click on the extension and "Inspect", then under "console" tab, copy and paste the error logs in red background here.

**Comment by mikef723** [comment]
Now I see an error log under Console.  I’ve copied and pasted as well as included a screenshot.  Please let me know how to fix this as soon as possible since I currently have no phone . . . .

from a content script:https://crm.redtailtechnology.com/dashboard/overview
sw.js:110 open popup
chrome-extension://invalid/:1


       Failed to load resource: net::ERR_FAILEDUnderstand this error
adapter.js:9911 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
_generateContentDOM @ adapter.js:9911Understand this warning
app.html:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.Understand this warning
adapter.js:56950 rc-dialer-status-notify: false
adapter.js:56953 rc-meeting-status-notify: false false
adapter.js:56916 rc-webphone-connection-status-notify:  connectionStatus-disconnected
popup.js:11886 rc-login-status-notify: false undefined undefined
adapter.js:56922 rc-login-status-notify: false undefined undefined
adapter.js:56944 rc-route-changed-notify: /
sw.js:253 from a content script:https://crm.redtailtechnology.com/dashboard/overview
sw.js:110 open popup
19Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.Understand this warning

***@***.***

**Comment by mikef723** [comment]
Please help.  I am not able to use my ringcentral with Redtail at all!

**Comment by DaKingKong** [comment]
@mikef723 

What version is your extension? The latest one is 1.0.1, and it should be fixed. If not, let's schedule a live debugging meeting to sort it out. Please contact me with your timezone and availability via da.kong@ringcentral.com

**Comment by mikef723** [comment]
I installed the latest version, the integration now works. Thank you.
