### ISSUE TITLE
Request: Wealthbox CRM integration

### ISSUE THREAD

**Issue by devtripp** [ringcentral/rc-unified-crm-extension#40]

**Comment by DaKingKong** [comment]
@devtripp 

Sorry for the late reply. We were preparing a proper feedback channel. Could you create a post in https://community.ringcentral.com/groups/unified-crm-extension-22? If possible, please provide more info regarding Wealthbox. While it's not necessary to do that, practically speaking, we are looking at many CRMs to integration, so it might eventually be a matter of priorities.
