### ISSUE TITLE
Unified CRM Auto Log issue

### ISSUE THREAD

**Issue by PX3med** [ringcentral/rc-unified-crm-extension#41]
![Unified CRM RingCentral Auto Call log Issue](https://github.com/ringcentral/rc-unified-crm-extension/assets/175168600/e4e8bfaf-0bfc-4960-818c-c809c50725be)

We are currently facing an issue with the unified CRM. When we make calls, the auto call log is not working and an error message pops up, stating: "Unresolved call logs are listed below. They cannot be auto-logged because of conflicts like multiple matched contacts, multiple associations, etc." However, there is only one account in the system with that person's name, and it always pulls the correct person when we go to resolve the logs. Any assistance to resolve this error message would be greatly appreciated!!

**Comment by DaKingKong** [comment]
@PX3med 

I guess you are using Bullhorn? If so, please take a look at https://ringcentral.github.io/rc-unified-crm-extension/bullhorn/#auto-log-with-default-note-action-preference-setup

**Comment by PX3med** [comment]
Correct Bullhorn is the CRM. Our team did try the instructions to apply the auto log toggle but they are still getting the "unresolved items due to conflicts over multiple Note Actions." for every call and text message.

Any other suggestions?


[cid:bfbe84b0-639d-4b1e-9dcf-8d268002a231]

Malina Avery

Project Manager

PX3 Medical

Phone: 925-948-8749<tel:925-891-3326>

Email: ***@***.******@***.***>

Calendly Linked HERE<https://calendly.com/malina-px3/45min?month=2023-10>

www.px3med.com<http://www.px3med.com/>



[##]<https://www.linkedin.com/in/jeremy-foley-7b878112/> [##] <https://www.youtube.com/channel/UCjUiYvfGE0na0qBV4hFONvw>  [##] <https://www.nrhapartners.com/partners/partnerDetail.php?p=eae27d77ca20db309e056e3d2dcd7d69&l=c81e728d9d4c2f636f067f89cc14862c>





***@***.***?anonymous&ep=owaSlotsEmailSignature>          Book time to meet with ***@***.***?anonymous&ep=owaSlotsEmailSignature>
________________________________

**Comment by DaKingKong** [comment]
@PX3med 

Not the toggle bit. This one:

The workaround: https://ringcentral.github.io/rc-unified-crm-extension/bullhorn/#auto-log-with-default-note-action-preference-setup

**Comment by DaKingKong** [comment]
@PX3med Sure. I'm in UTC+8 timezone though. Are you OK with time like your 8pm, so my 9am?

**Comment by PX3med** [comment]
Thank you.

We have a meeting set up with another representative.

Best,

[cid:aec1549a-c3af-477e-b4f7-6af2046d4efa]

Malina Avery

Project Manager

PX3 Medical

Phone: 925-948-8749<tel:925-891-3326>

Email: ***@***.******@***.***>

Calendly Linked HERE<https://calendly.com/malina-px3/45min?month=2023-10>

www.px3med.com<http://www.px3med.com/>



[##]<https://www.linkedin.com/in/jeremy-foley-7b878112/> [##] <https://www.youtube.com/channel/UCjUiYvfGE0na0qBV4hFONvw>  [##] <https://www.nrhapartners.com/partners/partnerDetail.php?p=eae27d77ca20db309e056e3d2dcd7d69&l=c81e728d9d4c2f636f067f89cc14862c>





***@***.***?anonymous&ep=owaSlotsEmailSignature>          Book time to meet with ***@***.***?anonymous&ep=owaSlotsEmailSignature>
________________________________

**Comment by DaKingKong** [comment]
@PX3med  Sure. I'll close this ticket for now. Contact me directly via da.kong@ringcentral.com if you have further questions.
