### ISSUE TITLE
Only see internal business contacts in CRM Chrome RingCentral App

### ISSUE THREAD

**Issue by cowboydaks** [ringcentral/rc-unified-crm-extension#5]
All of my business contacts are not showing in the RingCentral Chrome CRM Extension.  I see my contacts for the business and personal contacts in the desktop RingCentral app, but all of my contacts are not showing in the CRM Chrome RingCentral app.  I have connected the RingCentral Chrome CRM Extension also to my law practice management software made by Clio.  RingCentral desktop app is connected to Microsoft 365 and is syncing correctly.

Is there a way to see all my contacts in the CRM extension app, so I can make call log notes, dial by name, etc?

Thank you!

**Comment by cowboydaks** [comment]
while I can't see all my contacts, I have discovered that RingCentral CRM Chrome app only is recognizing numbers that have the following format in my contacts: +1 (XXX) XXX-XXXX.  I have MANY contacts and can't update each one to have this numbering format--is there a fix for this?  Thank you!

**Comment by DaKingKong** [comment]
contacted via email already
