### ISSUE TITLE
Clio Not Syncing Contacts

### ISSUE THREAD

**Issue by iprust** [ringcentral/rc-unified-crm-extension#8]
No contacts are coming over from Clio.  The only contacts I see are from RingCentral.  Every time I try to log a call, I get an error message saying to add the contact to the CRM.

**Comment by DaKingKong** [comment]
@iprust 

Contacts won't be listed within the extension. We recommend to use click-to-dial (hover mouse on Clio page's number and call with popup call button). All contacts info will be fetched in realtime when requested (eg. inbound/outbound call, call logging etc.). Clio's doesn't support phone number format. We added a workaround method. Details are here in "Phone number formats" section: https://ringcentral.github.io/rc-unified-crm-extension/configuration/

Or you can refer to this video guide: https://www.youtube.com/watch?v=pQgdsAR1UCI

**Comment by DaKingKong** [comment]
Closing this ticket as there's no further updates
